// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOS1CGhiAMjLlhKkzWiaxHBmIJkZIDCNM',
    appId: '1:654730206928:web:ed55cd94b28ab919f248d5',
    messagingSenderId: '654730206928',
    projectId: 'sahel-alik',
    authDomain: 'sahel-alik.firebaseapp.com',
    storageBucket: 'sahel-alik.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdOTPUkOE20jgv73QKGn0lHWj1rv57J30',
    appId: '1:654730206928:android:483d1b00156e6960f248d5',
    messagingSenderId: '654730206928',
    projectId: 'sahel-alik',
    storageBucket: 'sahel-alik.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrdofd4WOWYptLlwozQ0mjCPw-UwTJEwA',
    appId: '1:654730206928:ios:157e6c1e1fbd76f8f248d5',
    messagingSenderId: '654730206928',
    projectId: 'sahel-alik',
    storageBucket: 'sahel-alik.firebasestorage.app',
    iosBundleId: 'com.example.sahelAlik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrdofd4WOWYptLlwozQ0mjCPw-UwTJEwA',
    appId: '1:654730206928:ios:157e6c1e1fbd76f8f248d5',
    messagingSenderId: '654730206928',
    projectId: 'sahel-alik',
    storageBucket: 'sahel-alik.firebasestorage.app',
    iosBundleId: 'com.example.sahelAlik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOS1CGhiAMjLlhKkzWiaxHBmIJkZIDCNM',
    appId: '1:654730206928:web:042d0e3a61cd4f29f248d5',
    messagingSenderId: '654730206928',
    projectId: 'sahel-alik',
    authDomain: 'sahel-alik.firebaseapp.com',
    storageBucket: 'sahel-alik.firebasestorage.app',
  );
}
